version: '2.3'
services:
  stable-diffusion-webui:
    runtime: nvidia
    restart: always
    image: synthwave/stable-diffusion-webui
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "7860:7860"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
    volumes:
      - ../:/opt/stable-diffusion-webui
      - home:/root
    command: python3 /opt/stable-diffusion-webui/launch.py --no-half-vae --listen --api # --share
volumes:
  home:
networks:
  default:
    external:
      name: synthwave_network
